# Generated by Django 4.2.11 on 2024-08-05 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contact", "0002_contactrequest_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactrequest",
            name="lodge_reply",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
