# Generated by Django 4.2.11 on 2024-04-17 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_remove_reservation_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="guests",
        ),
        migrations.AddField(
            model_name="reservation",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="reservation",
            name="total_nights",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
