# Generated by Django 4.2.11 on 2024-04-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations",
            "0004_remove_reservation_guests_reservation_total_cost_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="total_nights",
            field=models.IntegerField(),
        ),
    ]
