# Generated by Django 4.2.11 on 2024-08-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations",
            "0005_reservation_status_alter_reservation_total_cost_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
