# Generated by Django 4.2.11 on 2024-08-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations",
            "0006_reservation_contact_number_reservation_first_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="contact_number",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="last_name",
        ),
    ]
