# Generated by Django 4.2.11 on 2024-04-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lodges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lodge",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Base rate per night",
                max_digits=7,
            ),
        ),
    ]
