# Generated by Django 4.2.11 on 2024-04-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lodges", "0002_lodge_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="lodge",
            name="sleeps",
            field=models.IntegerField(
                default=2, help_text="Number of guests the lodge sleeps"
            ),
            preserve_default=False,
        ),
    ]
