# Generated by Django 4.2.11 on 2024-04-17 18:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lodges", "0003_lodge_sleeps"),
    ]

    operations = [
        migrations.AddField(
            model_name="lodge",
            name="amenityImage1",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="lodge",
            name="amenityImage2",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
