# Generated by Django 4.2.11 on 2024-04-17 20:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lodges", "0004_lodge_amenityimage1_lodge_amenityimage2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lodge",
            name="amenityImage1",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, verbose_name="amenity image 1"
            ),
        ),
        migrations.AlterField(
            model_name="lodge",
            name="amenityImage2",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, verbose_name="amenity image 2"
            ),
        ),
    ]
