# Generated by Django 4.2.11 on 2024-04-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lodgeoverviews",
            options={"verbose_name_plural": "Lodge overview"},
        ),
    ]
