# Generated by Django 4.2.11 on 2024-04-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_lodgeoverviews_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="lodgeOverviews",
            new_name="LodgeOverview",
        ),
        migrations.AlterModelOptions(
            name="lodgeoverview",
            options={
                "verbose_name": "Lodge overview",
                "verbose_name_plural": "Lodge overview",
            },
        ),
    ]
