# Generated by Django 4.2.11 on 2024-04-08 22:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_lodgeoverviews_lodgeoverview_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lodgeoverview",
            name="description",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="lodgeoverview",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
