# Generated by Django 4.2.11 on 2024-08-05 14:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_lodgeoverview_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lodgeoverview",
            options={
                "verbose_name": "Lodge overview",
                "verbose_name_plural": "Lodge overviews",
            },
        ),
        migrations.AlterField(
            model_name="lodgeoverview",
            name="description",
            field=models.TextField(
                help_text="Enter a brief description of the lodge", max_length=400
            ),
        ),
        migrations.AlterField(
            model_name="lodgeoverview",
            name="image",
            field=cloudinary.models.CloudinaryField(
                help_text="Select an image for the lodge",
                max_length=255,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="lodgeoverview",
            name="name",
            field=models.CharField(
                help_text="Enter the name of the lodge", max_length=100
            ),
        ),
    ]
